"""Assistant-owned protocols for channels, queues, and product runtime."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class AssistantTurnServiceProtocol(Protocol):
    """定义通道适配器调用助手回合服务所需的最小接口。"""

    thinking: Any

    async def run_agent_with_thinking(
        self, user_input: str, *args: Any, **kwargs: Any
    ) -> Any: ...
    def inject_message(
        self, session_key: str, message: str, *args: Any, **kwargs: Any
    ) -> None: ...
    def get_thinking_display(self) -> Any: ...
    def session_turn(self, session_key: str) -> Any: ...
    def get_confirmation_channel(self, session_key: str) -> Any: ...
    def set_active_session_key(self, session_key: str | None) -> None: ...
    def clear_last_reflection(self, session_key: str) -> None: ...


@runtime_checkable
class ChannelRouterProtocol(Protocol):
    """定义外部通道与内部会话之间的绑定和解析接口。"""

    CLI_CHANNEL: str
    FEISHU_P2P_PREFIX: str
    FEISHU_GROUP_PREFIX: str

    def bind(self, channel_id: str, session_id: str) -> str: ...
    def unbind(self, channel_id: str) -> str: ...
    def resolve(self, channel_id: str) -> str: ...
    def get_bound_channels(self, session_id: str) -> list[str]: ...
    def set_primary(self, session_id: str) -> None: ...
    def get_primary(self) -> str | None: ...
    def resolve_feishu_message(
        self, chat_id: str, sender_id: str, chat_type: str = "group"
    ) -> str: ...
    def get_all_bindings(self) -> dict[str, str]: ...
    def is_bound(self, channel_id: str) -> bool: ...
    def status(self) -> str: ...


@runtime_checkable
class MessageQueueProtocol(Protocol):
    """定义按会话调度、取消和关停消息任务的队列接口。"""

    exec_lock: Any | None
    CLI_CHAT_ID: str
    mode: Any
    cross_queue_serial: bool

    def ensure_exec_lock(self) -> None: ...
    async def dispatch(
        self, chat_id: str, coro: Any, on_start: Any = None, on_done: Any = None
    ) -> None: ...
    async def dispatch_wait(
        self, chat_id: str, coro: Any, on_start: Any = None, on_done: Any = None
    ) -> None: ...
    def abort_chat(self, chat_id: str) -> dict[str, Any]: ...
    def abort_all_chats(self) -> dict[str, Any]: ...
    async def shutdown(self) -> dict[str, Any]: ...
    def get_status(self) -> dict[str, Any]: ...
    def get_agent_status(self, chat_id: str | None = None) -> dict[str, Any]: ...


@runtime_checkable
class FeishuRuntimeProtocol(Protocol):
    """定义飞书长连接运行时的启动、状态与关停接口。"""

    def start(
        self,
        create_handler: Any,
        state: dict | None = None,
        *,
        user_status: Callable[[str], None] | None = None,
    ) -> None: ...
    async def stop_async(self) -> None: ...
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
    def get_config(self) -> Any: ...
    def status(self) -> None: ...


__all__ = [
    "ChannelRouterProtocol",
    "FeishuRuntimeProtocol",
    "MessageQueueProtocol",
    "AssistantTurnServiceProtocol",
]
